# Official Arch repository.
official = [
    "starship",
    "zsh-syntax-highlighting",
    "zsh-autosuggestions",
    "exa",
    "bat",
    "pavucontrol",
    "virtualbox-host-modules-arch",
    "virtualbox",
    "unzip",
    "zip",
    "cloc",
    "htop",
    "isoimagewriter",
    "bats",
    "flatpak",
    "tree",
    "ufw",
]

# Arch user repository
aur = [
    "virtualbox-ext-oracle",
    "carapace-bin",
    "vesktop-bin",
    "ventoy-bin",
    "coppwr",
]
